# Generated by Django 5.0 on 2023-12-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10, verbose_name='Data da cotação do ativo')),
                ('open', models.CharField(max_length=10, verbose_name='Preço de abertura')),
                ('high', models.CharField(max_length=10, verbose_name='Preço mais alto')),
                ('low', models.CharField(max_length=10, verbose_name='Preço mais baixo')),
                ('close', models.CharField(max_length=10, verbose_name='Preço de fechamento')),
                ('adj_close', models.CharField(max_length=10, verbose_name='Preço adjacente de fechamento')),
                ('volume', models.CharField(max_length=20, verbose_name='Volume')),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
            },
        ),
    ]
